# -*- coding: utf-8 -*-
# Observation reference data for 2026-09-19 Paju session
#
# New fields per item:
#   visual  : 1-5 int, "안시관측 추천도" (5 = easiest/most rewarding to view with eye/small scope)
#   mag_num : float, brightest component magnitude, used for brightness sort
#   ra, dec : J2000 coordinates (decimal hours / degrees) used to compute tonight's
#             observing window via astro.py. Leave as None and set `win` instead for
#             solar-system objects whose position isn't fixed on the sky.
#   win     : optional manual override (start_hours_after_2000, end_hours_after_2000)

SESSION = {
    "date": "2026년 9월 19일 (토) 저녁 8시 ~ 9월 20일(일) 새벽 6시",
    "place": "대한민국 파주",
    "lat": 37.76,
    "lon": 126.78,
    "moon_illum": "약 51~56%",
    "moon_phase": "상현 지난 차가는 달 (Waxing Gibbous, 월령 약 8일)",
    "moonrise": "14:18",
    "moonset": "23:23",
    "sunset": "약 18:35",
    "astro_dusk": "약 19:55~20:05",
    "astro_dawn": "약 04:35~04:45",
    "sunrise": "약 06:04",
}

CATEGORIES = [
    {
        "id": "solar",
        "title": "태양계 천체",
        "emoji": "🌕",
        "desc": "이번 세션은 초저녁 달빛(23:23 몰)과 새벽의 행성 퍼레이드가 함께합니다.",
        "items": [
            dict(name_kr="달", name_en="The Moon", cat="위성", const="—",
                 mag="약 -11 등급 (해당 위상)", mag_num=-11.0, size="약 0.52° (30′)", dist="약 38만 km",
                 season="이 날은 20:00 관측 시작 시 이미 떠 있음 (몰입 23:23)",
                 visual=5, astro="best", astro_note="지형·크레이터·바다 경계 촬영에 최적",
                 note="월령 약 8일, 조명율 51~56%의 차가는 상현볼록달. 터미네이터(명암 경계선) 부근 크레이터 관측에 최적기입니다. 23:23 몰 이후에는 달빛 없이 딥스카이 관측이 가능해집니다.",
                 link="https://en.wikipedia.org/wiki/Moon", flag="달빛 방해: 20:00~23:23",
                 ra=None, dec=None, win=(0.0, 3.38)),
            dict(name_kr="토성", name_en="Saturn", cat="행성", const="물병자리(→물고기자리 경계)",
                 mag="약 +0.3~0.4 등급", mag_num=0.3, size="본체+고리 약 40″ (고리 기울기 약 7~8°)", dist="약 14.5억 km",
                 season="10/4 충 직전 — 이번 세션이 최적기, 초저녁부터 밤새 관측 가능",
                 visual=5, astro="best", astro_note="소구경으로도 고리 뚜렷, 행성 촬영(고배율 비디오 스태킹) 강력 추천",
                 note="가을철 밤하늘에서 가장 밝은 '별'입니다. 초저녁 남동쪽 하늘에 떠 있으며 자정 무렵 남중, 밤새 관측 가능합니다.",
                 link="https://en.wikipedia.org/wiki/Saturn",
                 ra=None, dec=None, win=(0.0, 10.0)),
            dict(name_kr="화성", name_en="Mars", cat="행성", const="쌍둥이자리",
                 mag="약 +1.0~1.1 등급", mag_num=1.0, size="시직경 약 4~5″ (매우 작음)", dist="—",
                 season="새벽 01:15경 동쪽에서 상승",
                 visual=4, astro="hard", astro_note="원반이 작아 세부 관측·촬영 모두 어려움 (고배율 비디오 촬영 권장)",
                 note="충을 지나 감광 중이라 밝지 않고 크기도 작습니다. 새벽 시간대, 카스토르·폴룩스 부근에서 찾을 수 있습니다.",
                 link="https://en.wikipedia.org/wiki/Mars",
                 ra=None, dec=None, win=(5.25, 10.0)),
            dict(name_kr="목성", name_en="Jupiter", cat="행성", const="쌍둥이자리→게자리 경계",
                 mag="약 -2.1 등급", mag_num=-2.1, size="시직경 약 33~35″", dist="—",
                 season="새벽 02:50~03:00경 동쪽 지평선 위로 상승, 여명 직전이 최적",
                 visual=4, astro="ok", astro_note="줄무늬·대적점은 고도가 오른 뒤가 유리, 갈릴레이 위성 4개는 쌍안경으로도 확인",
                 note="이날 새벽엔 고도가 낮아 대기 흔들림(시잉) 영향이 큽니다. 04:30 이후 여명 전 잠깐이 관측 적기입니다.",
                 link="https://en.wikipedia.org/wiki/Jupiter",
                 ra=None, dec=None, win=(6.83, 10.0)),
            dict(name_kr="천왕성", name_en="Uranus", cat="행성", const="황소자리 (알데바란-플레이아데스 사이)",
                 mag="약 5.7 등급", mag_num=5.7, size="시직경 약 3.5″", dist="—",
                 season="자정 이후~새벽, 황소자리가 충분히 뜬 뒤",
                 visual=2, astro="hard", astro_note="맨눈 한계 부근의 희미한 점, 별지도 대조 필수",
                 note="쌍안경/파인더로는 흐릿한 청록빛 '별'로만 보입니다. star-hopping으로 정확한 위치 확인이 필요합니다. (황소자리 고도를 기준으로 추정한 상승 시각)",
                 link="https://en.wikipedia.org/wiki/Uranus",
                 ra="ALDEBARAN_PROXY", dec=None, win=None),
            dict(name_kr="해왕성", name_en="Neptune", cat="행성", const="물고기자리",
                 mag="약 7.8 등급", mag_num=7.8, size="시직경 약 2.4″", dist="—",
                 season="9/26 충 — 이번 세션과 거의 동시기, 저녁부터 밤새 관측 가능",
                 visual=2, astro="hard", astro_note="150mm 이상 구경에서 작은 청회색 원반 확인 가능",
                 note="8행성 중 가장 어둡고 작지만, 마침 충 근접 시기라 이번이 일 년 중 보기 가장 좋은 시기입니다.",
                 link="https://en.wikipedia.org/wiki/Neptune",
                 ra=None, dec=None, win=(0.0, 10.0)),
        ],
    },
    {
        "id": "galaxy",
        "title": "은하",
        "emoji": "🌌",
        "desc": "가을철 대표 은하들. 달이 지는 23:30 이후, 최대한 어두운 하늘에서 시도하세요.",
        "items": [
            dict(name_kr="안드로메다은하", name_en="M31 · NGC 224", cat="나선은하", const="안드로메다자리",
                 mag="3.4 등급", mag_num=3.4, size="3.2° × 1° (190′×60′)", dist="약 250만 광년",
                 season="가을 전체(9~12월), 자정 남중은 11월경",
                 visual=5, astro="best", astro_note="맨눈 관측 가능한 유일한 외부은하 사진 대상, 광시야 렌즈로 위성은하(M32·M110)까지 한 프레임",
                 note="맨눈으로도 희미한 타원형 빛무리가 보이는 안시관측의 스테디셀러. 쌍안경으로 훨씬 크고 뚜렷해집니다.",
                 link="https://en.wikipedia.org/wiki/Andromeda_Galaxy",
                 ra=0.7123, dec=41.2692, win=None),
            dict(name_kr="삼각형자리은하", name_en="M33", cat="나선은하(정면)", const="삼각형자리",
                 mag="5.7 등급", mag_num=5.7, size="71′ × 42′", dist="약 288만 광년",
                 season="가을(9~11월), M31과 비슷한 시기",
                 visual=2, astro="hard", astro_note="표면밝기가 낮아 안시로는 매우 흐릿함 — 최대한 어두운 하늘·저배율 필수, 촬영은 오히려 잘 나오는 편",
                 note="등급 숫자보다 실제로 훨씬 희미하게 느껴지는 '까다로운' 대상입니다. 달이 완전히 진 뒤 도전하세요.",
                 link="https://en.wikipedia.org/wiki/Triangulum_Galaxy",
                 ra=1.5639, dec=30.6602, win=None),
            dict(name_kr="M74", name_en="Messier 74", cat="나선은하(정면)", const="물고기자리",
                 mag="9.4 등급", mag_num=9.4, size="10.5′ × 9.5′", dist="약 3,000만 광년",
                 season="가을~초겨울(10~11월)",
                 visual=1, astro="hard", astro_note="표면밝기가 매우 낮아 사진으로도 장노출이 필요한 대상",
                 note="메시에 천체 중 안시로 가장 어렵다고 알려진 대상 중 하나. 완전한 암소 하늘이 아니면 확인이 힘듭니다.",
                 link="https://en.wikipedia.org/wiki/Messier_74",
                 ra=1.6116, dec=15.7837, win=None),
            dict(name_kr="NGC 891", name_en="NGC 891", cat="나선은하(에지온)", const="안드로메다자리",
                 mag="10.8 등급", mag_num=10.8, size="13.5′ × 2.5′", dist="약 2,730만 광년",
                 season="가을~초겨울(10~12월)",
                 visual=2, astro="best", astro_note="칼날처럼 얇은 원반과 암흑대가 사진에서 인상적으로 담기는 인기 대상",
                 note="옆에서 본 나선은하로, 가운데를 가로지르는 암흑 먼지대가 특징. 안시로는 중형(200mm 이상) 망원경이 유리합니다.",
                 link="https://en.wikipedia.org/wiki/NGC_891",
                 ra=2.3759, dec=42.3492, win=None),
            dict(name_kr="NGC 7331", name_en="NGC 7331", cat="나선은하", const="페가수스자리",
                 mag="10.4 등급", mag_num=10.4, size="10.5′ × 3.7′", dist="약 4,400만 광년",
                 season="가을(9~11월)",
                 visual=3, astro="best", astro_note="'우리은하를 닮은 은하'로 유명, 스테판의 오중주와 한 프레임에 담는 촬영이 인기",
                 note="바로 옆(남서쪽 약 0.5°)에 스테판의 오중주가 있어 같은 시야에서 함께 찾아보기 좋습니다.",
                 link="https://en.wikipedia.org/wiki/NGC_7331",
                 ra=22.6178, dec=34.4158, win=None),
            dict(name_kr="스테판의 오중주", name_en="Stephan's Quintet", cat="컴팩트 은하군(5개)", const="페가수스자리",
                 mag="13.9~16.7 등급(개별)", mag_num=13.9, size="약 5′ 이내 밀집", dist="약 3.9억~2.1~3.4억 광년(구성원마다 다름)",
                 season="가을(9~11월)",
                 visual=1, astro="hard", astro_note="딥스카이 촬영 인기 대상이나 장초점·장노출 필요, 안시는 300mm 이상 대구경 권장",
                 note="좁은 시야에 은하 5개가 모여 있는 희귀한 광경. 안시로는 어렴풋한 얼룩들로만 보이는 상급자 대상입니다.",
                 link="https://en.wikipedia.org/wiki/Stephan%27s_Quintet",
                 ra=22.5993, dec=33.9600, win=None),
        ],
    },
    {
        "id": "nebula-diffuse",
        "title": "성운 — 산광성운 (발광/반사)",
        "emoji": "🎆",
        "desc": "여름철 은하수 자락의 대형 성운들. 필터(UHC/OIII) 사용 시 안시에서도 효과가 큽니다.",
        "items": [
            dict(name_kr="오리온성운", name_en="M42", cat="산광성운(발광+반사)", const="오리온자리",
                 mag="4.0 등급", mag_num=4.0, size="65′ × 60′", dist="약 1,340광년",
                 season="겨울 대표 성운(12~2월) — 이날은 새벽에 동쪽에서 낮게 상승",
                 visual=5, astro="best", astro_note="가장 인기 있는 딥스카이 촬영 대상, 트라페지움까지 안시로도 선명",
                 note="새벽 고도가 낮은 채로 잠깐 볼 수 있습니다. 본격적인 관측은 12~2월 저녁이 훨씬 유리합니다.",
                 link="https://en.wikipedia.org/wiki/Orion_Nebula",
                 ra=5.5880, dec=-5.3875, win=None),
            dict(name_kr="북아메리카 성운", name_en="NGC 7000", cat="산광성운(발광)", const="백조자리",
                 mag="4 등급(적분광도, 표면밝기는 낮음)", mag_num=4.0, size="120′ × 100′", dist="약 2,590광년",
                 season="여름~초가을(7~9월) — 이번 세션 초저녁이 마지막 적기",
                 visual=2, astro="best", astro_note="광시야 렌즈+Ha/듀오밴드 필터 촬영 대상 1순위, 안시는 대구경+OIII/UHC 성운필터 권장",
                 note="맨눈으로는 거의 안 보이지만 쌍안경+필터나 사진에서는 북미대륙 모양이 뚜렷합니다. 초저녁 서쪽으로 기울기 전에 보세요.",
                 link="https://en.wikipedia.org/wiki/North_America_Nebula",
                 ra=20.9881, dec=44.5289, win=None),
            dict(name_kr="펠리컨 성운", name_en="IC 5070", cat="산광성운(발광)", const="백조자리",
                 mag="8.0 등급(적분광도)", mag_num=8.0, size="60′ × 50′", dist="약 1,800광년",
                 season="여름~초가을(7~9월), 북아메리카 성운 바로 옆",
                 visual=1, astro="best", astro_note="북아메리카 성운과 한 프레임 촬영 가능, 안시는 매우 어려움(사진 전용에 가까움)",
                 note="북아메리카 성운 서쪽에 나란히 위치. 안시로는 대구경+필터로도 확인이 매우 까다롭습니다.",
                 link="https://en.wikipedia.org/wiki/Pelican_Nebula",
                 ra=20.8467, dec=44.3500, win=None),
            dict(name_kr="IC 1396 성운(가넷스타 부근)", name_en="IC 1396", cat="산광성운 + 산개성단", const="세페우스자리",
                 mag="약 3.5 등급(포함 성단 기준, 성운 자체는 매우 낮은 표면밝기)", mag_num=3.5, size="약 170′ × 140′ (약 3°)", dist="약 2,400광년",
                 season="늦여름~가을(8~10월), 세페우스자리는 연중 주극성",
                 visual=2, astro="best", astro_note="초광시야 렌즈+Ha 필터로 '코끼리 코 성운(IC1396A)'까지 인기 촬영 대상",
                 note="붉은 별 가넷스타(뮤 세페이)가 성운 가장자리에 걸쳐 있습니다. 성운 자체는 안시로 거의 보이지 않고, 포함된 성긴 산개성단만 확인됩니다.",
                 link="https://en.wikipedia.org/wiki/IC_1396",
                 ra=21.65, dec=57.5, win=None),
        ],
    },
    {
        "id": "nebula-planetary",
        "title": "성운 — 행성상성운",
        "emoji": "💍",
        "desc": "작고 밝은 대상이 많아 고배율 접안렌즈가 유리합니다. 대부분 장초점 촬영에 적합합니다.",
        "items": [
            dict(name_kr="고리성운", name_en="M57", cat="행성상성운", const="거문고자리",
                 mag="8.8 등급", mag_num=8.8, size="1.5′ × 1′ (약 84″×59″)", dist="약 2,570광년",
                 season="여름~가을(7~9월), 초저녁 머리 위 근처",
                 visual=4, astro="ok", astro_note="소형 망원경 고배율에서도 도넛 모양 뚜렷, 촬영은 장초점 권장",
                 note="가장 유명한 행성상성운. 초저녁 높은 고도에 있어 이번 세션 초반에 보기 좋습니다.",
                 link="https://en.wikipedia.org/wiki/Ring_Nebula",
                 ra=18.8931, dec=33.0292, win=None),
            dict(name_kr="아령성운", name_en="M27", cat="행성상성운", const="여우자리",
                 mag="7.4 등급", mag_num=7.4, size="8′ × 5.6′", dist="약 1,360광년",
                 season="여름~가을(7~9월)",
                 visual=5, astro="best", astro_note="행성상성운 중 가장 크고 밝아 사진·안시 모두 최우수 대상",
                 note="쌍안경으로도 아령 모양이 보일 만큼 밝고 큽니다. 초저녁 관측 리스트 중 최우선 추천 대상.",
                 link="https://en.wikipedia.org/wiki/Dumbbell_Nebula",
                 ra=19.9934, dec=22.7211, win=None),
            dict(name_kr="헬릭스 성운", name_en="NGC 7293", cat="행성상성운", const="물병자리",
                 mag="7.6 등급", mag_num=7.6, size="25′ (달의 약 5/6 크기)", dist="약 655광년",
                 season="가을(9~10월), 고도가 낮은 편이라 남쪽 하늘 트인 곳 필요",
                 visual=2, astro="ok", astro_note="가장 크고 지구에서 가장 가까운 행성상성운, 저배율 광시야+필터 촬영 유리",
                 note="크기는 크지만 표면밝기가 낮아 은근히 까다롭습니다. 남쪽 지평선이 트인 곳에서 시도하세요.",
                 link="https://en.wikipedia.org/wiki/Helix_Nebula",
                 ra=22.4941, dec=-20.8371, win=None),
            dict(name_kr="깜빡이 행성상성운", name_en="NGC 6826 (Blinking Planetary)", cat="행성상성운", const="백조자리",
                 mag="8.8 등급", mag_num=8.8, size="27″ × 24″", dist="약 2,000광년",
                 season="여름~가을(7~9월)",
                 visual=4, astro="ok", astro_note="작아서 장초점 필요, 안시에서는 직시/사시(회피시)로 밝기가 바뀌는 '깜빡임' 관찰이 포인트",
                 note="중심별을 직접 보면 성운이 희미해지고 살짝 옆을 보면 밝아지는 재미있는 착시 효과가 유명합니다.",
                 link="https://en.wikipedia.org/wiki/NGC_6826",
                 ra=19.7467, dec=50.5251, win=None),
            dict(name_kr="토성 성운", name_en="NGC 7009 (Saturn Nebula)", cat="행성상성운", const="물병자리",
                 mag="8.0 등급", mag_num=8.0, size="41″ × 35″ (양쪽 돌기 포함 약 1.7′)", dist="약 2,000~4,000광년",
                 season="가을(9~10월)",
                 visual=4, astro="ok", astro_note="고배율에서 양옆 돌기(고리 흔적)까지 보이는 촬영 인기 대상",
                 note="고배율에서 토성처럼 양옆으로 돌기가 뻗어 나온 모습이 보입니다. 200mm 이상 구경을 권장합니다.",
                 link="https://en.wikipedia.org/wiki/Saturn_Nebula",
                 ra=21.0697, dec=-11.3634, win=None),
            dict(name_kr="태아 성운", name_en="NGC 7008 (Fetus Nebula)", cat="행성상성운", const="백조자리",
                 mag="12.0 등급", mag_num=12.0, size="1.4′ × 1.1′", dist="약 2,800광년",
                 season="여름~가을(7~9월)",
                 visual=2, astro="hard", astro_note="어둡고 작아 촬영도 장노출·장초점 필요",
                 note="목록 중 가장 어두운 행성상성운. 대구경 망원경과 어두운 하늘이 필요합니다.",
                 link="https://en.wikipedia.org/wiki/NGC_7008",
                 ra=21.0090, dec=54.5434, win=None),
            dict(name_kr="블루 스노볼 성운", name_en="NGC 7662 (Blue Snowball)", cat="행성상성운", const="안드로메다자리",
                 mag="8.3 등급", mag_num=8.3, size="32″ × 28″", dist="약 5,730광년",
                 season="가을~초겨울(10~12월)",
                 visual=4, astro="ok", astro_note="작고 파란 원반이 사진에서 또렷하게 담김, 장초점 권장",
                 note="이름처럼 푸르스름한 눈덩이 색이 특징적인 작고 밝은 행성상성운입니다.",
                 link="https://en.wikipedia.org/wiki/NGC_7662",
                 ra=23.4316, dec=42.5350, win=None),
            dict(name_kr="에스키모 성운", name_en="NGC 2392 (Eskimo/Clown Face)", cat="행성상성운", const="쌍둥이자리",
                 mag="9.1 등급", mag_num=9.1, size="48″ × 48″", dist="약 6,520광년",
                 season="겨울(1~2월) — 이날은 새벽에 화성 근처로 낮게 떠오름",
                 visual=3, astro="ok", astro_note="털모자를 쓴 얼굴 같은 구조가 촬영에서 인상적, 고배율·장초점 필요",
                 note="새벽 시간대, 화성이 있는 쌍둥이자리 부근에서 함께 찾아볼 수 있습니다.",
                 link="https://en.wikipedia.org/wiki/Eskimo_Nebula",
                 ra=7.4863, dec=20.9118, win=None),
        ],
    },
    {
        "id": "cluster-globular",
        "title": "성단 — 구상성단",
        "emoji": "🔮",
        "desc": "가을철 하늘의 대표 구상성단 두 곳입니다.",
        "items": [
            dict(name_kr="M15", name_en="Messier 15", cat="구상성단", const="페가수스자리",
                 mag="6.2 등급", mag_num=6.2, size="18′", dist="약 3만 3,600광년",
                 season="가을(9~11월)",
                 visual=4, astro="ok", astro_note="중심부가 매우 밀집되어 있어 고배율 촬영·안시 모두 인상적",
                 note="은하수 구상성단 중 핵심부 밀도가 가장 높은 축에 속합니다. 중형 망원경에서 알갱이처럼 분해되기 시작합니다.",
                 link="https://en.wikipedia.org/wiki/Messier_15",
                 ra=21.4995, dec=12.1670, win=None),
            dict(name_kr="M2", name_en="Messier 2", cat="구상성단", const="물병자리",
                 mag="6.5 등급", mag_num=6.5, size="16′", dist="약 3만 8,100광년",
                 season="가을(8~10월)",
                 visual=4, astro="ok", astro_note="M15와 비슷한 밝기·크기, 촬영 시 별상 분해가 매력",
                 note="M15와 함께 가을철 대표 구상성단으로 꼽히며 밝기와 크기가 비슷해 비교 관측하기 좋습니다.",
                 link="https://en.wikipedia.org/wiki/Messier_2",
                 ra=21.5575, dec=-0.8233, win=None),
        ],
    },
    {
        "id": "cluster-sagittarius",
        "title": "성단 — 궁수자리·방패자리 그룹 (초저녁 우선 관측!)",
        "emoji": "🏹",
        "desc": "이 대상들은 여름철이 최적기라 9월 저녁엔 이미 남서쪽 하늘 낮게 걸려 있습니다. 20:00~21:30 사이, 가장 먼저 관측하세요.",
        "items": [
            dict(name_kr="야생오리 성단", name_en="M11 (Wild Duck Cluster)", cat="산개성단", const="방패자리",
                 mag="5.8 등급", mag_num=5.8, size="22.8′", dist="약 6,120광년",
                 season="여름(6~8월) — 9/19 초저녁이 마지막 관측 기회",
                 visual=5, astro="best", astro_note="메시에 산개성단 중 가장 밀집도가 높아 마치 구상성단처럼 보이는 인기 촬영 대상",
                 note="부채꼴로 퍼진 별들이 날아가는 오리떼를 닮았다 하여 붙은 이름. 목록 중 가장 촘촘한 산개성단입니다.",
                 link="https://en.wikipedia.org/wiki/Wild_Duck_Cluster", flag="초저녁 낮은 고도, 서두르세요",
                 ra=18.8514, dec=-6.2700, win=None),
            dict(name_kr="M26", name_en="Messier 26", cat="산개성단", const="방패자리",
                 mag="8.0 등급", mag_num=8.0, size="14′", dist="약 5,160광년",
                 season="여름(6~8월)",
                 visual=3, astro="ok", astro_note="M11보다 성기고 어두워 안시 위주",
                 note="M11에서 남동쪽으로 멀지 않은 곳에 있는 비교적 어두운 산개성단입니다.",
                 link="https://en.wikipedia.org/wiki/Messier_26", flag="초저녁 낮은 고도",
                 ra=18.7550, dec=-9.3833, win=None),
            dict(name_kr="M23", name_en="Messier 23", cat="산개성단", const="궁수자리",
                 mag="5.5 등급", mag_num=5.5, size="35′", dist="약 2,050광년",
                 season="여름(6~8월)",
                 visual=4, astro="ok", astro_note="넓은 시야에 걸쳐 별이 흩어져 있어 광시야 촬영에 적합",
                 note="150개 이상의 별이 넓게 퍼진 크고 성긴 산개성단입니다.",
                 link="https://en.wikipedia.org/wiki/Messier_23", flag="초저녁 낮은 고도",
                 ra=17.9511, dec=-18.9850, win=None),
            dict(name_kr="M25", name_en="Messier 25 (IC 4725)", cat="산개성단", const="궁수자리",
                 mag="4.6 등급", mag_num=4.6, size="36′", dist="약 2,000광년",
                 season="여름(6~8월)",
                 visual=4, astro="ok", astro_note="쌍안경 시야에 잘 맞는 크기, 광시야 촬영 적합",
                 note="쌍안경으로도 별이 잘 분해되는 밝고 큰 산개성단입니다.",
                 link="https://en.wikipedia.org/wiki/Messier_25", flag="초저녁 낮은 고도",
                 ra=18.5297, dec=-19.1167, win=None),
            dict(name_kr="M18", name_en="Messier 18", cat="산개성단", const="궁수자리",
                 mag="7.5 등급", mag_num=7.5, size="9.8′", dist="약 4,230광년",
                 season="여름(6~8월)",
                 visual=3, astro="ok", astro_note="M17(오메가성운)과 M24 사이, 광시야 딥스카이 사진의 경유지",
                 note="비교적 어리고 성긴 산개성단으로, 오메가성운과 M24 사이 길목에 있습니다.",
                 link="https://en.wikipedia.org/wiki/Messier_18", flag="초저녁 낮은 고도",
                 ra=18.3328, dec=-17.1017, win=None),
            dict(name_kr="작은 궁수자리 스타클라우드", name_en="M24", cat="성운상 항성운(스타클라우드)", const="궁수자리",
                 mag="4.5 등급(전체)", mag_num=4.5, size="120′ × 60′ (약 2°×1°)", dist="1만~1.5만 광년(폭 방향)",
                 season="여름(6~8월)",
                 visual=5, astro="best", astro_note="쌍안경·저배율 광시야 촬영에 최고의 은하수 대상, 수많은 별이 배경 성운처럼 뭉쳐 보임",
                 note="성단이 아니라 우리은하 원반의 별들이 창문처럼 뚫려 보이는 '스타클라우드'입니다. 쌍안경으로 보면 압도적입니다.",
                 link="https://en.wikipedia.org/wiki/Small_Sagittarius_Star_Cloud", flag="초저녁 낮은 고도",
                 ra=18.2819, dec=-18.5142, win=None),
        ],
    },
    {
        "id": "cluster-cygnus",
        "title": "성단 — 백조자리·여우자리·거문고자리 그룹",
        "emoji": "🦢",
        "desc": "초저녁부터 머리 위 은하수를 따라 늘어선 산개성단들. 이번 세션 초·중반의 주력 대상입니다.",
        "items": [
            dict(name_kr="옷걸이 성단", name_en="Collinder 399 (Brocchi's Cluster / Coathanger)", cat="애스터리즘", const="여우자리",
                 mag="3.6 등급", mag_num=3.6, size="약 60′", dist="구성 별마다 235~1,735광년으로 제각각",
                 season="여름~가을(7~9월)",
                 visual=5, astro="best", astro_note="쌍안경·저배율 광시야에 옷걸이 모양이 그대로 담기는 인기 대상",
                 note="실제 성단이 아니라 우연히 늘어선 별들의 모임(애스터리즘)입니다. 쌍안경으로 보면 정말 옷걸이 모양입니다.",
                 link="https://en.wikipedia.org/wiki/Brocchi%27s_Cluster",
                 ra=19.4233, dec=20.1833, win=None),
            dict(name_kr="M39", name_en="Messier 39", cat="산개성단", const="백조자리",
                 mag="4.6 등급", mag_num=4.6, size="29′ (보름달 크기)", dist="약 1,010광년",
                 season="여름~가을(8~10월)",
                 visual=4, astro="ok", astro_note="성긴 삼각형 모양, 저배율·쌍안경 위주",
                 note="느슨하게 흩어진 밝은 별들로 이루어져 저배율 쌍안경 관측에 잘 맞습니다.",
                 link="https://en.wikipedia.org/wiki/Messier_39",
                 ra=21.5300, dec=48.4333, win=None),
            dict(name_kr="M29", name_en="Messier 29", cat="산개성단", const="백조자리",
                 mag="7.1 등급", mag_num=7.1, size="7′", dist="약 5,240광년",
                 season="여름~가을(7~9월)",
                 visual=3, astro="ok", astro_note="작고 아담해 촬영 시 다른 대상과 함께 담기 좋음",
                 note="백조자리 감마별(사드르) 근처의 작고 아담한 산개성단입니다.",
                 link="https://en.wikipedia.org/wiki/Messier_29",
                 ra=20.3989, dec=38.5233, win=None),
            dict(name_kr="NGC 6811 (Hole in a Cluster)", name_en="NGC 6811", cat="산개성단", const="백조자리",
                 mag="6.8 등급", mag_num=6.8, size="13′", dist="약 3,600광년",
                 season="여름~가을(7~9월)",
                 visual=3, astro="ok", astro_note="가운데 별이 성긴 '구멍' 구조가 사진에서 특징적",
                 note="중심부에 별이 적어 도넛처럼 가운데가 비어 보이는 독특한 구조로 유명합니다.",
                 link="https://en.wikipedia.org/wiki/NGC_6811",
                 ra=19.6214, dec=46.3883, win=None),
            dict(name_kr="NGC 6819 (Foxhead Cluster)", name_en="NGC 6819", cat="산개성단", const="백조자리",
                 mag="7.3 등급", mag_num=7.3, size="5′", dist="약 7,200광년",
                 season="여름~가을(7~9월)",
                 visual=3, astro="ok", astro_note="작고 밀집되어 장초점 촬영에 적합",
                 note="크기는 작지만 별이 촘촘히 모여 있어 중배율 관측에 좋습니다.",
                 link="https://en.wikipedia.org/wiki/NGC_6819",
                 ra=19.6883, dec=40.1867, win=None),
            dict(name_kr="NGC 6871", name_en="NGC 6871", cat="산개성단", const="백조자리",
                 mag="5.2 등급", mag_num=5.2, size="9.3′", dist="약 5,130광년",
                 season="여름~가을(7~9월)",
                 visual=3, astro="ok", astro_note="젊고 밝은 별로 구성, 주변 성운과 함께 촬영하기 좋음",
                 note="맨눈 한계에 가까운 밝기의 젊은 산개성단으로, 쌍안경으로 쉽게 확인됩니다.",
                 link="https://en.wikipedia.org/wiki/NGC_6871",
                 ra=20.0997, dec=35.7772, win=None),
            dict(name_kr="NGC 6940", name_en="NGC 6940", cat="산개성단", const="여우자리",
                 mag="6.3 등급", mag_num=6.3, size="25′", dist="약 2,510광년",
                 season="여름~가을(8~10월)",
                 visual=4, astro="ok", astro_note="넓고 별이 많아 광시야 촬영에 적합",
                 note="상당히 크고 별이 풍부해 쌍안경으로도 인상적인 모습을 보여줍니다.",
                 link="https://en.wikipedia.org/wiki/NGC_6940",
                 ra=20.5739, dec=28.2833, win=None),
            dict(name_kr="알비레오 (이중성)", name_en="Albireo (β Cygni)", cat="이중성", const="백조자리",
                 mag="주성 3.2 / 동반성 5.8 등급", mag_num=3.2, size="—", dist="약 380광년", sep="35″",
                 season="여름~가을(6~9월)",
                 visual=5, astro="visual", astro_note="색 대비를 눈으로 감상하는 안시 대표 대상, 사진은 와이드필드 스타필드 정도",
                 note="금색과 파란색 별이 나란히 있는, 밤하늘에서 가장 아름다운 이중성으로 꼽힙니다. 소형 망원경으로도 쉽게 분리됩니다.",
                 link="https://en.wikipedia.org/wiki/Albireo",
                 ra=19.5120, dec=27.9597, win=None),
            dict(name_kr="61 Cygni (이중성)", name_en="61 Cygni", cat="이중성", const="백조자리",
                 mag="A 5.2 / B 6.1 등급", mag_num=5.2, size="—", dist="약 11.4광년(태양 인접 항성)", sep="약 16~20″",
                 season="여름~가을(7~10월)",
                 visual=4, astro="visual", astro_note="안시 전용, 두 별 모두 주황색 K형 별이라 색 대비는 크지 않음",
                 note="태양계에서 15번째로 가까운 항성계이자, 가장 큰 고유운동을 가진 육안 별로 유명합니다.",
                 link="https://en.wikipedia.org/wiki/61_Cygni",
                 ra=21.1152, dec=38.7456, win=None),
            dict(name_kr="ε Lyrae (더블더블 스타)", name_en="Epsilon Lyrae", cat="다중성(이중의 이중성)", const="거문고자리",
                 mag="ε¹: 4.7/6.2, ε²: 5.1/5.5 등급", mag_num=4.7, size="—", dist="약 160광년", sep="넓은 쌍 208″ · 각 쌍 내부 약 2.3~2.4″",
                 season="여름~가을(6~9월), 직녀성(베가) 바로 옆",
                 visual=3, astro="visual", astro_note="고배율 접안(150배 이상)로 4개 별 모두 분리해보는 안시 챌린지 대상",
                 note="쌍안경으로 이중성처럼 보이지만, 고배율 망원경으로 보면 각 별이 다시 이중성으로 갈라지는 '더블더블'입니다.",
                 link="https://en.wikipedia.org/wiki/Epsilon_Lyrae",
                 ra=18.7390, dec=39.6701, win=None),
        ],
    },
    {
        "id": "cluster-cassiopeia",
        "title": "성단 — 카시오페아·페르세우스 그룹 (연중 관측 가능·주극성)",
        "emoji": "🐉",
        "desc": "카시오페아자리는 파주(북위 약 37.8°)에서 주극성이라 밤새 지지 않습니다. 밤이 깊을수록 고도가 높아져 후반부 관측에 유리합니다.",
        "items": [
            dict(name_kr="페르세우스 이중성단", name_en="NGC 869 & NGC 884 (Double Cluster)", cat="산개성단(쌍)", const="페르세우스자리",
                 mag="3.7 / 3.8 등급", mag_num=3.7, size="합쳐서 약 60′", dist="약 7,500광년",
                 season="가을~겨울(10~1월)",
                 visual=5, astro="best", astro_note="망원경 시야 하나에 두 성단이 동시에 들어오는 최고의 촬영·안시 대상",
                 note="맨눈으로도 뿌연 얼룩 두 개가 보이며, 쌍안경으로는 별들이 폭죽처럼 쏟아지는 장관입니다. 이번 목록의 하이라이트 중 하나.",
                 link="https://en.wikipedia.org/wiki/Double_Cluster",
                 ra=2.3333, dec=57.1333, win=None),
            dict(name_kr="ET 성단", name_en="NGC 457 (Owl / ET Cluster)", cat="산개성단", const="카시오페아자리",
                 mag="6.4 등급", mag_num=6.4, size="20′", dist="약 7,900광년",
                 season="연중 가능(주극성), 가을~겨울 고도 최적",
                 visual=5, astro="best", astro_note="눈(밝은 별 2개)과 팔 벌린 몸통 형태가 사진·안시 모두에서 뚜렷",
                 note="영화 ET 캐릭터를 닮았다 하여 붙은 애칭으로 유명한, 인상적인 모양의 산개성단입니다.",
                 link="https://en.wikipedia.org/wiki/NGC_457",
                 ra=1.3257, dec=58.2908, win=None),
            dict(name_kr="NGC 7789 (캐롤라인의 장미)", name_en="NGC 7789", cat="산개성단", const="카시오페아자리",
                 mag="6.7 등급", mag_num=6.7, size="16′", dist="약 7,600광년",
                 season="가을~겨울(10~12월)",
                 visual=4, astro="best", astro_note="수많은 희미한 별이 장미 꽃잎처럼 퍼진 구조가 사진에서 아름답게 표현됨",
                 note="발견자 캐롤라인 허셜의 이름을 딴 별칭처럼, 촘촘한 별들이 꽃송이 모양을 이룹니다.",
                 link="https://en.wikipedia.org/wiki/NGC_7789",
                 ra=23.9567, dec=56.7083, win=None),
            dict(name_kr="M52", name_en="Messier 52", cat="산개성단", const="카시오페아자리",
                 mag="7.3 등급", mag_num=7.3, size="13′", dist="약 4,600광년",
                 season="가을~겨울(9~12월)",
                 visual=4, astro="ok", astro_note="NGC7789와 한 쌍으로 자주 촬영되는 대상",
                 note="상대적으로 젊고 촘촘한 산개성단으로, NGC7789와 함께 카시오페아 관측 투어에 좋습니다.",
                 link="https://en.wikipedia.org/wiki/Messier_52",
                 ra=23.4133, dec=61.5933, win=None),
            dict(name_kr="NGC 663", name_en="NGC 663", cat="산개성단", const="카시오페아자리",
                 mag="7.1 등급", mag_num=7.1, size="16′", dist="약 8,800광년",
                 season="가을~겨울(10~1월)",
                 visual=4, astro="ok", astro_note="주변 NGC 654·659와 함께 광시야 한 프레임 촬영에 적합",
                 note="맨눈 한계에 가까운 밝은 산개성단으로, 이웃한 NGC654·659와 함께 은하수 감상에 좋습니다.",
                 link="https://en.wikipedia.org/wiki/NGC_663",
                 ra=1.7667, dec=61.25, win=None),
            dict(name_kr="NGC 654", name_en="NGC 654", cat="산개성단", const="카시오페아자리",
                 mag="6.5 등급", mag_num=6.5, size="6′", dist="약 7,800광년",
                 season="가을~겨울(10~1월)",
                 visual=3, astro="ok", astro_note="NGC663 인근 소형 성단, 광시야 사진에서 조연으로 등장",
                 note="NGC 663 바로 근처의 작고 아담한 산개성단입니다.",
                 link="https://en.wikipedia.org/wiki/NGC_654",
                 ra=1.7333, dec=61.885, win=None),
            dict(name_kr="NGC 659", name_en="NGC 659", cat="산개성단", const="카시오페아자리",
                 mag="7.9 등급", mag_num=7.9, size="6′", dist="약 8,200광년",
                 season="가을~겨울(10~1월)",
                 visual=2, astro="hard", astro_note="어둡고 작아 안시 위주",
                 note="NGC654·663과 이웃한 세 번째 소형 산개성단으로, 목록 중 가장 어둡습니다.",
                 link="https://en.wikipedia.org/wiki/NGC_659",
                 ra=1.7344, dec=60.6667, win=None),
            dict(name_kr="NGC 7788 + NGC 7790", name_en="NGC 7788 / NGC 7790", cat="산개성단(쌍)", const="카시오페아자리",
                 mag="9.4 / 8.5 등급", mag_num=8.5, size="2.4′ / 7.4′", dist="— / 약 1만 800광년",
                 season="가을~겨울(10~1월)",
                 visual=2, astro="hard", astro_note="작고 어두워 장초점 촬영 대상, 소형 망원경 안시로는 뿌옇게만 확인",
                 note="두 성단이 가까이 붙어 있어 한 시야에서 함께 찾을 수 있는 상급자용 소형 산개성단 쌍입니다.",
                 link="https://en.wikipedia.org/wiki/NGC_7790",
                 ra=23.9734, dec=61.2083, win=None),
            dict(name_kr="Stock 2 (근육맨 성단)", name_en="Stock 2 (Muscleman Cluster)", cat="산개성단", const="카시오페아자리/페르세우스자리 경계",
                 mag="약 4.4 등급(약식)", mag_num=4.4, size="약 60′(약식)", dist="약 1,000광년 내외(약식)",
                 season="가을~겨울(10~1월)",
                 visual=4, astro="ok", astro_note="크고 성긴 구조라 쌍안경·광시야 촬영에 적합",
                 note="이중성단 바로 옆, 넓게 흩어진 별들이 팔다리를 벌린 사람 모양(근육맨)처럼 보인다는 애칭이 있습니다. 정밀 수치는 카탈로그마다 다소 차이가 있어 참고용입니다.",
                 link="https://en.wikipedia.org/wiki/Stock_2", flag="수치 약식(카탈로그 간 편차 있음)",
                 ra=2.25, dec=59.2667, win=None),
            dict(name_kr="알마크 (이중성)", name_en="Almach (γ Andromedae)", cat="이중성", const="안드로메다자리",
                 mag="A 2.3 / B 5.0(BC 합) 등급", mag_num=2.3, size="—", dist="약 390광년", sep="9.6″ (A–BC)",
                 season="가을~초겨울(10~12월)",
                 visual=5, astro="visual", astro_note="금색·청색 대비가 알비레오급으로 아름다운 안시 대표 이중성",
                 note="알비레오와 쌍벽을 이루는 색 대비 이중성으로, 금빛 주성과 푸른 동반성이 소형 망원경으로도 잘 분리됩니다.",
                 link="https://en.wikipedia.org/wiki/Almach",
                 ra=2.0650, dec=42.3297, win=None),
            dict(name_kr="가넷 스타 (석류의 별)", name_en="Mu Cephei (Garnet Star)", cat="변광성(적색초거성)", const="세페우스자리",
                 mag="3.4~5.1 등급(변광)", mag_num=3.4, size="—", dist="약 1,370광년",
                 season="연중 가능(주극성), 가을 고도 최적",
                 visual=4, astro="ok", astro_note="깊은 붉은색이 특징이라 컬러 사진·아이피스 색 감상 모두에 인상적",
                 note="윌리엄 허셜이 '석류석 색'이라 표현한 짙은 붉은빛의 초거성입니다. 저배율로 색을 감상하는 것이 포인트입니다.",
                 link="https://en.wikipedia.org/wiki/Mu_Cephei",
                 ra=21.7251, dec=58.7800, win=None),
        ],
    },
    {
        "id": "cluster-winter",
        "title": "성단 — 겨울철 그룹 (자정~새벽 상승)",
        "emoji": "❄️",
        "desc": "황소자리·마차부자리·쌍둥이자리 대상들. 자정 이후 동쪽 하늘에서 순서대로 떠오릅니다.",
        "items": [
            dict(name_kr="플레이아데스 성단", name_en="M45 (Pleiades)", cat="산개성단", const="황소자리",
                 mag="1.6 등급", mag_num=1.6, size="2°", dist="약 444광년",
                 season="겨울(11~1월) — 이날은 밤 11시경부터 동쪽에서 상승",
                 visual=5, astro="best", astro_note="파란 반사성운기까지 담기는 최고 인기 촬영 대상, 광시야 렌즈 필수",
                 note="맨눈으로 6~7개 별이 보이는 좀생이별. 쌍안경으로 보면 수십 개의 파란 별이 보석함처럼 펼쳐집니다.",
                 link="https://en.wikipedia.org/wiki/Pleiades",
                 ra=3.7772, dec=24.1781, win=None),
            dict(name_kr="프레세페 성단", name_en="M44 (Beehive Cluster)", cat="산개성단", const="게자리",
                 mag="3.7 등급", mag_num=3.7, size="95′ (1.5°)", dist="약 610광년",
                 season="봄(2~4월) — 이날은 새벽에야 겨우 상승, 관측 난이도 높음",
                 visual=4, astro="ok", astro_note="쌍안경·광시야 촬영에 적합, 넓게 퍼져 있어 저배율 필수",
                 note="벌집처럼 별이 밀집된 대형 산개성단이나, 9월 세션에서는 새벽 낮은 고도에서만 잠깐 볼 수 있습니다.",
                 link="https://en.wikipedia.org/wiki/Beehive_Cluster", flag="새벽에도 고도 낮음",
                 ra=8.6733, dec=19.9833, win=None),
            dict(name_kr="M35", name_en="Messier 35", cat="산개성단", const="쌍둥이자리",
                 mag="5.3 등급", mag_num=5.3, size="28′", dist="약 2,970광년",
                 season="겨울(12~2월) — 자정 이후 상승",
                 visual=5, astro="best", astro_note="사슬처럼 이어진 별줄이 촬영에서 매력적, 옆의 소형성단 NGC2158과 대비",
                 note="보름달만 한 크기에 밝은 별들이 흩어져 있어 쌍안경으로도 훌륭합니다.",
                 link="https://en.wikipedia.org/wiki/Messier_35",
                 ra=6.1483, dec=24.3333, win=None),
            dict(name_kr="M41", name_en="Messier 41", cat="산개성단", const="큰개자리",
                 mag="4.5 등급", mag_num=4.5, size="38′", dist="약 2,360광년",
                 season="겨울(1~2월) — 새벽에도 고도가 매우 낮음",
                 visual=4, astro="ok", astro_note="시리우스 남쪽, 낮은 고도 때문에 촬영 난이도 있음",
                 note="시리우스 바로 남쪽에 있어 맨눈으로도 흐릿하게 보입니다. 이번 세션에서는 새벽에도 지평선에 가까워 관측이 어려울 수 있습니다.",
                 link="https://en.wikipedia.org/wiki/Messier_41", flag="새벽에도 지평선 근접, 관측 어려움",
                 ra=6.7667, dec=-20.7667, win=None),
            dict(name_kr="M36", name_en="Messier 36", cat="산개성단", const="마차부자리",
                 mag="6.3 등급", mag_num=6.3, size="12′", dist="약 4,340광년",
                 season="겨울(12~2월) — 자정 이후 상승",
                 visual=4, astro="ok", astro_note="M37·M38과 나란히 삼형제 촬영 세트로 인기",
                 note="마차부자리 삼형제 성단 중 가장 성긴 편으로, 젊고 파란 별들이 특징입니다.",
                 link="https://en.wikipedia.org/wiki/Messier_36",
                 ra=5.6050, dec=34.1400, win=None),
            dict(name_kr="M37", name_en="Messier 37", cat="산개성단", const="마차부자리",
                 mag="6.2 등급", mag_num=6.2, size="24′", dist="약 4,510광년",
                 season="겨울(12~2월)",
                 visual=5, astro="best", astro_note="마차부 삼형제 중 가장 크고 별이 풍부해 촬영·안시 모두 최고 인기",
                 note="마차부자리 삼형제 성단 중 가장 화려하고 별이 많아 소형 망원경에서도 인상적입니다.",
                 link="https://en.wikipedia.org/wiki/Messier_37",
                 ra=5.8717, dec=32.5506, win=None),
            dict(name_kr="M38", name_en="Messier 38", cat="산개성단", const="마차부자리",
                 mag="7.4 등급", mag_num=7.4, size="21′", dist="약 3,480광년",
                 season="겨울(12~2월)",
                 visual=4, astro="ok", astro_note="십자(X)형 별 배열이 특징적인 촬영 대상",
                 note="별들이 십자 또는 파이(π) 모양으로 배열되어 보이는 것이 특징인 마차부 삼형제 중 하나입니다.",
                 link="https://en.wikipedia.org/wiki/Messier_38",
                 ra=5.4786, dec=35.8550, win=None),
            dict(name_kr="Kemble's Cascade", name_en="Kemble's Cascade", cat="애스터리즘", const="기린자리",
                 mag="5~10 등급 별들의 사슬", mag_num=5.0, size="약 3° (직선상)", dist="—",
                 season="겨울 중심(11~2월), 기린자리는 준주극성이라 밤새 관측 가능",
                 visual=5, astro="best", astro_note="쌍안경 시야에 꼭 맞는 별들의 폭포수 모양, 저배율 촬영·안시 모두 인기",
                 note="약 20개의 별이 일직선으로 늘어서 마치 폭포처럼 쏟아지는 모습을 보여주는 아름다운 애스터리즘입니다. 끝에는 NGC1502 산개성단이 있습니다.",
                 link="https://en.wikipedia.org/wiki/Kemble%27s_Cascade",
                 ra=4.0, dec=63.0, win=None),
        ],
    },
    {
        "id": "star-polaris",
        "title": "그 밖의 이중성",
        "emoji": "⭐",
        "desc": "북극성은 밤새 거의 같은 자리에 있어 언제든 확인할 수 있습니다.",
        "items": [
            dict(name_kr="Polaris (북극성 이중성)", name_en="Polaris (α UMi)", cat="이중성", const="작은곰자리",
                 mag="A 2.0 / B 8.7 등급", mag_num=2.0, size="—", dist="약 447광년", sep="18.2″",
                 season="연중 항상 같은 고도(북위 약 37.8°)",
                 visual=3, astro="visual", astro_note="안시 확인용, 밝기 차가 커서 소형 망원경 고배율 필요",
                 note="북극성 자체는 밝지만 동반성은 8등급으로 어두워 밝기 차이가 큰 이중성입니다. 소형 망원경으로 도전해볼 만합니다.",
                 link="https://en.wikipedia.org/wiki/Polaris",
                 ra=2.5303, dec=89.2641, win=None),
        ],
    },
]
